endOfLine: lf
printWidth: 120
useTabs: false
semi: false
singleQuote: false
jsxSingleQuote: false
arrowParens: avoid
trailingComma: all
overrides:
  - files: "**/(*.json|*.yaml|*.yml|.babelrc|.prettierrc|.eslintrc)"
    options:
      useTabs: false
